### ISSUE TITLE
Build of master4.9 fails on Debian jessie

### ISSUE THREAD

**Issue by mark0n** [epicsdeb/rtems#5]
Package builds fine on wheezy but fails on jessie:

```
==> jessie: make[3]: Nothing to be done for 'install-exec-am'.
==> jessie: make[3]: Nothing to be done for 'install-data-am'.
==> jessie: make[3]: Leaving directory '/home/vagrant/rtems/build-m68k'
==> jessie: make[2]: Leaving directory '/home/vagrant/rtems/build-m68k'
==> jessie: make[1]: Leaving directory '/home/vagrant/rtems/build-m68k'
==> jessie: mv debian/tmp/usr/bin/bin2boot debian/tmp/usr/bin/i386-rtems4.9-bin2boot
==> jessie: mv: 
==> jessie: cannot stat ‘debian/tmp/usr/bin/bin2boot’
==> jessie: : No such file or directory
==> jessie: debian/rules:75: recipe for target 'install-stamp' failed
==> jessie: make: *** [install-stamp] Error 1
==> jessie: dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
==> jessie: debuild: fatal error at line 1376:
==> jessie: dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
==> jessie: gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29
```

**Comment by mdavidsaver** [comment]
Well this is a puzzle because it works for me

> make[4]: Leaving directory '/tmp/buildd/rtems-4.9.6/build-m68k'
> make[3]: Leaving directory '/tmp/buildd/rtems-4.9.6/build-m68k'
> make[2]: Leaving directory '/tmp/buildd/rtems-4.9.6/build-m68k'
> mv debian/tmp/usr/bin/bin2boot debian/tmp/usr/bin/i386-rtems4.9-bin2boot
> rm -rf /tmp/buildd/rtems-4.9.6/debian/tmp/usr/share/man
> make[1]: Leaving directory '/tmp/buildd/rtems-4.9.6'

Built from 6b2dc4c16812ef337a7b4ae70e097c7bc3a0941d for jessie amd64 w/ pbuilder.  Do you have local changes?

**Comment by mark0n** [comment]
You're right. We had changes in our FRIB repo. Sorry about the noise...
